/**
 * Dependency service port interfaces — defines the data-access contract
 * required by the DependencyService for DAG validation and dependency
 * management.
 *
 * These interfaces follow the same hexagonal architecture pattern used by
 * other application-layer ports: narrow, operation-specific contracts that
 * decouple the service from infrastructure details.
 *
 * @see docs/prd/002-data-model.md §2.3 — TaskDependency entity and DAG rules
 * @module @factory/application/ports/dependency.ports
 */

import type { DependencyType } from "@factory/domain";

// ---------------------------------------------------------------------------
// Entity shapes — minimal fields the dependency service needs
// ---------------------------------------------------------------------------

/**
 * A dependency edge as seen by the dependency service.
 *
 * Represents a directed edge in the task dependency graph where
 * `taskId` depends on `dependsOnTaskId`.
 */
export interface DependencyEdge {
  readonly taskDependencyId: string;
  readonly taskId: string;
  readonly dependsOnTaskId: string;
  readonly dependencyType: DependencyType;
  readonly isHardBlock: boolean;
  readonly createdAt: Date;
}

/**
 * Data required to create a new dependency edge.
 * The `taskDependencyId` and `createdAt` are generated by the repository.
 */
export interface NewDependencyEdge {
  readonly taskDependencyId: string;
  readonly taskId: string;
  readonly dependsOnTaskId: string;
  readonly dependencyType: DependencyType;
  readonly isHardBlock: boolean;
}

// ---------------------------------------------------------------------------
// Repository ports
// ---------------------------------------------------------------------------

/**
 * Port for task existence checks within the dependency service.
 *
 * The dependency service needs to verify that both task IDs in a
 * dependency edge actually exist before inserting.
 */
export interface DependencyTaskRepositoryPort {
  /** Check whether a task with the given ID exists. */
  exists(id: string): boolean;
}

/**
 * Port for task dependency data access within the dependency service.
 *
 * Provides forward and reverse graph traversal, plus edge creation
 * and deletion. These are the operations needed for DAG validation
 * and dependency management.
 */
export interface TaskDependencyRepositoryPort {
  /**
   * Forward lookup: find all dependencies of a given task.
   * Returns edges where `taskId` is the dependent (waiting) task.
   */
  findByTaskId(taskId: string): DependencyEdge[];

  /**
   * Reverse lookup: find all tasks that depend on a given task.
   * Returns edges where `dependsOnTaskId` is the prerequisite task.
   */
  findByDependsOnTaskId(dependsOnTaskId: string): DependencyEdge[];

  /**
   * Find a specific dependency edge between two tasks.
   * Returns undefined if no edge exists.
   */
  findByTaskIdPair(taskId: string, dependsOnTaskId: string): DependencyEdge | undefined;

  /** Insert a new dependency edge. Returns the inserted row. */
  create(data: NewDependencyEdge): DependencyEdge;

  /** Delete a dependency edge by primary key. Returns true if deleted. */
  delete(taskDependencyId: string): boolean;
}

// ---------------------------------------------------------------------------
// Unit of Work for dependency operations
// ---------------------------------------------------------------------------

/**
 * Repository collection available inside a dependency transaction.
 */
export interface DependencyTransactionRepositories {
  readonly task: DependencyTaskRepositoryPort;
  readonly taskDependency: TaskDependencyRepositoryPort;
}

/**
 * Unit of work for dependency operations.
 *
 * Wraps dependency mutations in a transaction to ensure atomicity
 * of the cycle-check + insert sequence.
 */
export interface DependencyUnitOfWork {
  runInTransaction<T>(fn: (repos: DependencyTransactionRepositories) => T): T;
}
