/**
 * Repository port interfaces for the transition service.
 *
 * These interfaces define the minimal data-access contract that the
 * transition service requires. They are intentionally narrow — each
 * port exposes only the operations needed for state transitions, not
 * the full CRUD surface of the underlying repositories.
 *
 * Infrastructure implementations (in apps/control-plane) satisfy these
 * ports, keeping the application layer decoupled from database details.
 *
 * @see docs/prd/007-technical-architecture.md §7.5 — Layered architecture
 * @module @factory/application/ports/repository.ports
 */

import type {
  TaskStatus,
  WorkerLeaseStatus,
  ReviewCycleStatus,
  MergeQueueItemStatus,
} from "@factory/domain";

// ---------------------------------------------------------------------------
// Shared entity shapes — the minimal fields the transition service reads
// ---------------------------------------------------------------------------

/**
 * Minimal task record required by the transition service.
 * The full entity may have many more fields; the port only exposes
 * what transitions need.
 */
export interface TransitionableTask {
  readonly id: string;
  readonly status: TaskStatus;
  readonly version: number;
}

/**
 * Minimal task lease record required by the transition service.
 * Uses status-based optimistic concurrency (no version column).
 */
export interface TransitionableTaskLease {
  readonly id: string;
  readonly status: WorkerLeaseStatus;
}

/**
 * Minimal review cycle record required by the transition service.
 * Uses status-based optimistic concurrency (no version column).
 */
export interface TransitionableReviewCycle {
  readonly id: string;
  readonly status: ReviewCycleStatus;
}

/**
 * Minimal merge queue item record required by the transition service.
 * Uses status-based optimistic concurrency (no version column).
 */
export interface TransitionableMergeQueueItem {
  readonly id: string;
  readonly status: MergeQueueItemStatus;
}

/**
 * Audit event record as persisted. Returned by the repository after creation.
 */
export interface AuditEventRecord {
  readonly id: string;
  readonly entityType: string;
  readonly entityId: string;
  readonly eventType: string;
  readonly actorType: string;
  readonly actorId: string;
  readonly oldState: string | null;
  readonly newState: string | null;
  readonly metadata: string | null;
  readonly createdAt: Date;
}

/**
 * Input for creating a new audit event. The `id` and `createdAt` are
 * generated by the repository implementation.
 */
export interface NewAuditEvent {
  readonly entityType: string;
  readonly entityId: string;
  readonly eventType: string;
  readonly actorType: string;
  readonly actorId: string;
  readonly oldState: string | null;
  readonly newState: string | null;
  readonly metadata: string | null;
}

// ---------------------------------------------------------------------------
// Repository ports
// ---------------------------------------------------------------------------

/**
 * Port for task data access within a transition.
 *
 * `updateStatus` performs an optimistic concurrency check using the
 * task's `version` column. If `expectedVersion` does not match the
 * current version in the database, it must throw a `VersionConflictError`.
 */
export interface TaskRepositoryPort {
  findById(id: string): TransitionableTask | undefined;
  updateStatus(id: string, expectedVersion: number, newStatus: TaskStatus): TransitionableTask;
}

/**
 * Port for task lease data access within a transition.
 *
 * `updateStatus` performs a status-based optimistic concurrency check.
 * If the entity's current status does not match `expectedStatus`, it
 * must throw a `VersionConflictError`.
 */
export interface TaskLeaseRepositoryPort {
  findById(id: string): TransitionableTaskLease | undefined;
  updateStatus(
    id: string,
    expectedStatus: WorkerLeaseStatus,
    newStatus: WorkerLeaseStatus,
  ): TransitionableTaskLease;
}

/**
 * Port for review cycle data access within a transition.
 *
 * `updateStatus` performs a status-based optimistic concurrency check.
 * If the entity's current status does not match `expectedStatus`, it
 * must throw a `VersionConflictError`.
 */
export interface ReviewCycleRepositoryPort {
  findById(id: string): TransitionableReviewCycle | undefined;
  updateStatus(
    id: string,
    expectedStatus: ReviewCycleStatus,
    newStatus: ReviewCycleStatus,
  ): TransitionableReviewCycle;
}

/**
 * Port for merge queue item data access within a transition.
 *
 * `updateStatus` performs a status-based optimistic concurrency check.
 * If the entity's current status does not match `expectedStatus`, it
 * must throw a `VersionConflictError`.
 */
export interface MergeQueueItemRepositoryPort {
  findById(id: string): TransitionableMergeQueueItem | undefined;
  updateStatus(
    id: string,
    expectedStatus: MergeQueueItemStatus,
    newStatus: MergeQueueItemStatus,
  ): TransitionableMergeQueueItem;
}

/**
 * Port for audit event persistence.
 * Audit events are append-only — no update or delete.
 */
export interface AuditEventRepositoryPort {
  create(event: NewAuditEvent): AuditEventRecord;
}
